app = "ai-face-swap-app"
primary_region = "ewr"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false        # ← CHANGED: Disable auto-stopping
  min_machines_running = 2          # ← CHANGED: Keep 2 machines running
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

[[vm]]
  memory = "4gb"
  cpu_kind = "shared"
  cpus = 2          # ← Change this from 1 to 2

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

# Postgres internal service (Flycast resolution) - LEAVE THIS AS-IS
[[services]]
  internal_port = 5432
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = true
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]