# Generated by Django 5.1.6 on 2025-07-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="featured_video_url",
            field=models.URLField(blank=True),
        ),
    ]
